econordeste/blog/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

from econordeste.blog.views import (EntryYearArchiveView,
                                    EntryMonthArchiveView,
                                    EntryDayArchiveView, EntryListView,
                                    EntryDateDetailView, EntryTagListView,
                                    EntryCategoryListView)


urlpatterns = patterns(
    'econordeste.blog.views',
    url(r'^$', EntryListView.as_view(), name='home'),
    url(r'^(?P<year>\d{4})/$',
        EntryYearArchiveView.as_view(),
        name='entry_archive_year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d+)/$',
        EntryMonthArchiveView.as_view(month_format='%m'),
        name='entry_archive_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d+)/(?P<day>\d+)/$',
        EntryDayArchiveView.as_view(month_format='%m'),
        name='entry_archive_day'),
    url(r'^(?P<year>\d{4})/(?P<month>\d+)/(?P<day>\d+)/(?P<slug>[-\w]+)/$',
        EntryDateDetailView.as_view(month_format='%m'),
        name='entry_date_detail'),
    url(r'^marcacao/(?P<tag_slug>[-\w]+)/$', EntryTagListView.as_view(),
        name='tag_list'),
    url(r'^categoria/(?P<cat_slug>[-\w]+)/$', EntryCategoryListView.as_view(),
        name='category_list'),
)

econordeste/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from filebrowser.sites import site

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^$', 'econordeste.core.views.home', name='home'),
    # url(r'^institucional/', 'canaa.core.views.institutional',
    #     name='institutional'),
    url(r'^projeto/$', 'econordeste.core.views.project', name='project'),
    url(r'^soundcloud/$', 'econordeste.core.views.soundcloud',
        name='soundcloud'),
    url(r'^equipe/$', 'econordeste.core.views.team', name='team'),
    url(r'^jogos/$', 'econordeste.core.views.games', name='games'),
    url(r'^contato/$', 'econordeste.core.views.contact', name='contact'),

    url(r'^noticias/', include('econordeste.blog.urls', namespace='blog')),
    url(r'^agenda/', include('econordeste.event.urls', namespace='event')),

    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # tinymce
    url(r'^tinymce/', include('tinymce.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# )

econordeste/core/models.py
# coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

import uuid
import os

from filebrowser.fields import FileBrowseField
from sorl.thumbnail import ImageField
from tinymce import models as tinymce_models

try:
    from PIL import Image, ImageOps
except ImportError:
    import Image
    import ImageOps


STATE_CHOICES = (
    ('AC', u'Acre'),
    ('AL', u'Alagoas'),
    ('AP', u'Amapá'),
    ('AM', u'Amazonas'),
    ('BA', u'Bahia'),
    ('CE', u'Ceará'),
    ('DF', u'Distrito Federal'),
    ('ES', u'Espírito Santo'),
    ('GO', u'Goiás'),
    ('MA', u'Maranhão'),
    ('MT', u'Mato Grosso'),
    ('MS', u'Mato Grosso do Sul'),
    ('MG', u'Minas Gerais'),
    ('PA', u'Pará'),
    ('PB', u'Paraíba'),
    ('PR', u'Paraná'),
    ('PE', u'Pernambuco'),
    ('PI', u'Piauí'),
    ('RJ', u'Rio de Janeiro'),
    ('RN', u'Rio Grande do Norte'),
    ('RS', u'Rio Grande do Sul'),
    ('RO', u'Rondônia'),
    ('RR', u'Roraima'),
    ('SC', u'Santa Catarina'),
    ('SP', u'São Paulo'),
    ('SE', u'Sergipe'),
    ('TO', u'Tocantins'),
)

BANNER_CHOICES = (
    (1, _(u'Super Banner (Home)')),
    # (2, _(u'Banner Secundário (Home)')),
    (3, _(u'Popup Banner')),
)


class Social(models.Model):
    name = models.CharField(_(u'Nome'), max_length=50,
                            help_text='Ex: Facebook')
    link = models.URLField(_(u'Link'),
                           help_text='Ex: http://www.facebook.com/usuario')

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Mídia Social')
        verbose_name_plural = _(u'Mídias Sociais')
        ordering = ['name']


class Enterprise(models.Model):
    name = models.CharField(_(u'Nome'), max_length=100)
    description = models.CharField(_(u'Descrição'), max_length=100,
                                   blank=True, null=True)
    cnpj = models.CharField(_(u'CNPJ'), max_length=20,
                            help_text='99.999.999/9999-99')
    address = models.CharField(_(u'Endereço'), max_length=200)
    number = models.CharField(_(u'Número'), max_length=10)
    complement = models.CharField(_(u'Complemento'), max_length=100,
                                  blank=True, null=True)
    cep = models.CharField(_(u'CEP'), max_length=9, help_text='99999-999',
                           blank=True, null=True)
    district = models.CharField(_(u'Bairro'), max_length=100)
    city = models.CharField(_(u'Cidade'), max_length=100)
    state = models.CharField(_(u'UF'), max_length=2, choices=STATE_CHOICES)
    country = models.CharField(_(u'País'), max_length=50)
    phone1 = models.CharField(_(u'Fone 1'), max_length=20,
                              help_text='(99) 9999-9999')
    phone2 = models.CharField(_(u'Fone 2'), max_length=20,
                              help_text='(99) 9999-9999', blank=True,
                              null=True)
    phone3 = models.CharField(_(u'Fone 3 (Fax)'), max_length=20,
                              help_text='(99) 9999-9999', blank=True,
                              null=True)
    email = models.EmailField(_(u'Email'))
    site = models.URLField(_(u'Site'))
    socials = models.ManyToManyField('Social',
                                     verbose_name=_(u'Mídias Sociais'))

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Empresa')
        verbose_name_plural = _(u'Empresa')


class Category(models.Model):
    name = models.CharField(_(u'Nome da Categoria'), max_length=200)
    slug = models.SlugField(_(u'Link no Site'), max_length=200,
                            unique=True)
    acronym = models.CharField(_(u'Sigla'), max_length=50, blank=True,
                               null=True)

    def get_absolute_url(self):
        return reverse('blog:category_list', kwargs={'pk': self.pk})

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Categoria')
        verbose_name_plural = _(u'Categorias')
        ordering = ['name']


class BannerManager(models.Manager):
    def get_queryset(self):
        return super(BannerManager,
                     self).get_queryset().all()


class BannerPublishedManager(models.Manager):
    def get_queryset(self):
        return super(BannerPublishedManager,
                     self).get_queryset().filter(publish=True)


class Banner(models.Model):
    def get_file_path(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), ext)
        return os.path.join('banner', filename)

    type = models.IntegerField(_(u'Banner'), choices=BANNER_CHOICES, default=1)
    image = ImageField(_(u'Banner'), upload_to=get_file_path)
    title = models.CharField(_(u'Título do banner'), max_length=100)
    link = models.URLField(_(u'Link do banner'), blank=True, null=True)
    publish = models.BooleanField(_(u'Visível no site?'), default=True)

    objects = BannerManager()
    published = BannerPublishedManager()

    def admin_image(self):
        return '<img src="%s" width="200" />' % self.image.url
    admin_image.allow_tags = True
    admin_image.short_description = 'Imagem'

    def save(self, *args, **kwargs):
        if not self.id and not self.image:
            return

        super(Banner, self).save(*args, **kwargs)

        image = Image.open(self.image)

        def scale_dimensions(width, height, longest_side):
            if width > height:
                if width > longest_side:
                    ratio = longest_side*1./width
                    return (int(width*ratio), int(height*ratio))
                elif height > longest_side:
                    ratio = longest_side*1./height
                    return (int(width*ratio), int(height*ratio))
            return (width, height)

        if self.type == 2:
            side = 500
        else:
            side = 1280

        (width, height) = image.size
        (width, height) = scale_dimensions(width, height, longest_side=side)

        size = (width, height)
        """ redimensiona esticando """
        # image = image.resize(size, Image.ANTIALIAS)
        """ redimensiona proporcionalmente """
        image.thumbnail(size, Image.ANTIALIAS)
        """ redimensiona cortando para encaixar no tamanho """
        # image = ImageOps.fit(image, size, Image.ANTIALIAS)
        image.save(self.image.path, 'JPEG', quality=99)

    def __unicode__(self):
        return unicode(self.title)

    class Meta:
        verbose_name = _(u'Banner')
        verbose_name_plural = _(u'Banners')


class Team(models.Model):
    def get_file_path(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), ext)
        return os.path.join('team', filename)

    name = models.CharField(_(u'Nome'), max_length=30)
    description = models.CharField(_(u'Descrição'), max_length=200)
    image = models.ImageField(_(u'Foto'), upload_to=get_file_path,
                              blank=True, null=True)

    def admin_image(self):
        if self.image.url:
            return '<img src="%s" width="60" />' % self.image.url
        else:
            return 'Sem imagem.'
    admin_image.allow_tags = True
    admin_image.short_description = 'Foto'

    def save(self, *args, **kwargs):
        if not self.id and not self.image:
            return

        super(Team, self).save(*args, **kwargs)

        image = Image.open(self.image)

        def scale_dimensions(width, height, longest_side):
            if width > height:
                if width > longest_side:
                    ratio = longest_side*1./width
                    return (int(width*ratio), int(height*ratio))
                elif height > longest_side:
                    ratio = longest_side*1./height
                    return (int(width*ratio), int(height*ratio))
            return (width, height)

        side = 400

        (width, height) = image.size
        (width, height) = scale_dimensions(width, height, longest_side=side)

        size = (width, height)
        """ redimensiona esticando """
        # image = image.resize(size, Image.ANTIALIAS)
        """ redimensiona proporcionalmente """
        # image.thumbnail(size, Image.ANTIALIAS)
        """ redimensiona cortando para encaixar no tamanho """
        image = ImageOps.fit(image, size, Image.ANTIALIAS)
        image.save(self.image.path, 'JPEG', quality=99)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _(u'Equipe')
        verbose_name_plural = _(u'Equipe')
        ordering = ['name']


class Project(models.Model):
    title = models.CharField(_(u'Título'), max_length=200)
    body = tinymce_models.HTMLField(_(u'Conteúdo'))

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _(u'Projeto')
        verbose_name_plural = _(u'Projeto')
        ordering = ['title']


class Games(models.Model):
    title = models.CharField(_(u'Título'), max_length=200)
    body = tinymce_models.HTMLField(_(u'Conteúdo'))

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _(u'Jogo')
        verbose_name_plural = _(u'Jogos')
        ordering = ['title']


class Video(models.Model):
    title = models.CharField(_(u'Título'), max_length=100)
    body = models.TextField(_(u'Descrição'), blank=True, null=True)
    url = models.URLField(_(u'Endereço do Vídeo'))
    embed = models.URLField(_(u'Embed'), blank=True, null=True, editable=False)

    def __unicode__(self):
        return unicode(self.title)

    def save(self, *args, **kwargs):
        self.embed = self.url.replace('watch?v=', 'embed/')
        super(Video, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _(u'Vídeo')
        verbose_name_plural = _(u'Vídeos')
        ordering = ['-pk']


class Logo(models.Model):

econordeste/blog/forms.py
# coding: utf-8
from django import forms
from tinymce.widgets import TinyMCE

from econordeste.event.models import Calendar


class CalendarModelForm(forms.ModelForm):
    body = forms.CharField(widget=TinyMCE(
                           attrs={'cols': 100, 'rows': 50}))

    class Meta:
        model = Calendar

econordeste/blog/views.py
# coding: utf-8
from django.db.models import Q
from django.views import generic
from django.views.generic.dates import (YearArchiveView, MonthArchiveView,
                                        DayArchiveView)

from econordeste.context_processors import EnterpriseExtraContext

from econordeste.blog.models import Entry
from econordeste.core.models import Category


class EntryYearArchiveView(YearArchiveView):
    queryset = Entry.published.all()
    date_field = 'created'
    make_object_list = True
    allow_future = True
    # TODO: mudar a paginacao
    paginate_by = 10


class EntryMonthArchiveView(MonthArchiveView):
    queryset = Entry.published.all()
    date_field = 'created'
    make_object_list = True
    allow_future = True


class EntryDayArchiveView(DayArchiveView):
    queryset = Entry.published.all()
    date_field = 'created'
    make_object_list = True
    allow_future = True


class EntryListView(EnterpriseExtraContext,  generic.ListView):
    # model = Entry
    queryset = Entry.published.all()
    template_name = 'blog/entry_home.html'
    # TODO: mudar a paginacao
    paginate_by = 6

    def get_queryset(self, **kwargs):
        search = self.request.GET.get('search', '')
        if search:
            obj_lst = Entry.published.filter(Q(title__icontains=search) |
                                             Q(created__icontains=search) |
                                             Q(body__icontains=search))
        else:
            obj_lst = Entry.published.all()
        return obj_lst

    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        search = self.request.GET.get('search', '')
        context['search'] = search
        context['tag_list'] = Entry.tags.most_common()
        # TODO: mudar a forma de carregamento das categorias
        context['category_list'] = Category.objects.all().order_by('?')[:10]
        return context


class EntryDateDetailView(EnterpriseExtraContext, generic.DateDetailView):
    # model = Entry
    queryset = Entry.published.all()
    date_field = 'created'
    make_object_list = True
    allow_future = True

    def get_context_data(self, **kwargs):
        context = super(EntryDateDetailView, self).get_context_data(**kwargs)
        context['tag_list'] = Entry.tags.most_common()
        # TODO: mudar a forma de carregamento das categorias
        context['category_list'] = Category.objects.all().order_by('?')[:10]
        return context


class EntryTagListView(EntryListView):
    """
    Herda de EntryListView mudando o filtro para tag selecionada
    """
    def get_queryset(self):
        """
        Incluir apenas as Entries marcadas com a tag selecionada
        """
        return Entry.published.filter(tags__slug=self.kwargs['tag_slug'])


class EntryCategoryListView(EntryListView):
    """
    Herda de EntryListView mudando o filtro para categoria selecionada
    """
    def get_queryset(self, **kwargs):
        """
        Inclui apenas as Entries marcadas com a categoria selecionada
        """
        return Entry.published.filter(categories__slug=self.kwargs['cat_slug'])

econordeste/blog/templates/blog/entry_archive_day.html
<h1>{{ day }}</h1>

<ul>
    {% for article in object_list %}
        <li>{{ article.pub_date|date:"F j, Y" }}: {{ article.title }}</li>
    {% endfor %}
</ul>

<p>
    {% if previous_day %}
        Previous Day: {{ previous_day }}
    {% endif %}
    {% if previous_day and next_day %}--{% endif %}
    {% if next_day %}
        Next Day: {{ next_day }}
    {% endif %}
</p>

econordeste/blog/templates/blog/entry_archive_month.html
<ul>
    {% for article in object_list %}
        <li>{{ article.pub_date|date:"F j, Y" }}: {{ article.title }}</li>
    {% endfor %}
</ul>

<p>
    {% if previous_month %}
        Previous Month: {{ previous_month|date:"F Y" }}
    {% endif %}
    {% if next_month %}
        Next Month: {{ next_month|date:"F Y" }}
    {% endif %}
</p>

econordeste/blog/templates/blog/entry_archive_year.html
<ul>
    {% for date in date_list %}
        <li>{{ date|date }}</li>
    {% endfor %}
</ul>

<div>
    <h1>All Articles for {{ year|date:"Y" }}</h1>
    {% for obj in object_list %}
        <p>
            {{ obj.title }} - {{ obj.pub_date|date:"F j, Y" }}
        </p>
    {% endfor %}
</div>

{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endif %}

econordeste/blog/templates/blog/entry_base.html
{% extends "base.html" %}

{% load thumbnail %}

{% block nav_blog %} active{% endblock %}

{% block content %}

			<!-- Inner Page Content // Start -->

			<div class="inner-page">
				<div class="container">
					<div class="row">
						<!-- Main-bar Column -->
						<div class="col-md-12">
							<div class="page-mainbar blog">
								<!-- Heading -->
								<h3>Notícias <small class="white">{% if search %}busca por "{{ search }}"{% endif %}</small></h3>
								<!-- Blog Page Content -->
								<div class="blog-content">
									<div class="row">
										<div class="col-md-9 col-sm-9">

											{% block post %}

											{% endblock post %}

											<div class="clearfix"></div>
											<!-- Blog post End -->
										</div>
										<div class="col-md-3 col-sm-3">
											<div class="blog-sidebar black">
												<!-- Sidebar widget -->
												<!-- First -->
												<div class="side-widget br-white">
													<h4>Busca</h4>
													<div class="widget-content">
														<!-- search button and input box -->
														<form role="form" action="." method="get" class="form-inline bform">
															<!-- /input-group -->
															<div class="input-group">
																<input id="search" name="search" type="text" class="form-control" placeholder="Buscar Notícia">
																<span class="input-group-btn">
																	<button class="btn btn-default" type="submit">Buscar</button>
																</span>
															</div><!-- /input-group -->
														</form>
													</div>
												</div>
												<!-- Second -->
												<div class="side-widget br-white">
													<h4>Vídeos</h4>
													<div class="widget-content">
														{% for video in video_list %}
															<iframe width="100%" height="200" src="{{ video.embed }}" frameborder="0" allowfullscreen></iframe><br>
														{% endfor %}
													</div>
												</div>
												<!-- Third -->
												<div class="side-widget br-white">
													<h4>Categorias</h4>
													<div class="widget-content">
														<ol>
															{% for cat in category_list %}
						                                        <li><a href="{% url 'blog:category_list' cat.slug %}">{{ cat.name }}</a></li>
						                                    {% endfor %}
														</ol>
													</div>
												</div>
												<!-- Quarter -->
												<div class="side-widget br-white">
													<h4>Marcações</h4>
													<div class="widget-content">
														{% for tag in tag_list %}
					                                        <a href="{% url 'blog:tag_list' tag.slug %}">{{ tag }}</a>
					                                    {% endfor %}
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Inner Page Content // End -->

{% endblock content %}

econordeste/blog/templates/blog/entry_detail.html
{% extends "blog/entry_base.html" %}

{% load thumbnail %}

{% block nav_blog %} active{% endblock %}

{% block post %}

	<!-- The new post done by user's all in the post block -->
	<div class="blog-post">
		<!-- Entry is the one post for each user -->
		<div class="entry">
			<!-- Meta for this block -->
            <div class="col-md-3 col-sm-3">
    			<div class="meta br-white">
    				<!-- Date -->
    				<div class="post-date"><span>{{ object.created|date:"d M" }}</span>{{ object.created|date:"Y" }}</div>
    				<!-- Post Information -->
    				<div class="meta-info"><i class="fa fa-user"></i> <span>{{ object.author }}</span></div>
    				<div class="meta-info"><i class="fa fa-tag"></i>
    					{% for tag in object.tags.all %}
    				        <a href="{% url 'blog:tag_list' tag.slug %}"><span>{{ tag.name }}</span></a>
                        {% endfor %}
    				</div>
    				<div class="clearfix"></div>
    			</div>
            </div>
            <div class="col-md-9 col-sm-9">
    			<div class="beta br-white pull-right">
    				<!-- Heading of the  post -->
    				<h4><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h4>
    				{% thumbnail object.image "1000" crop="center" format="PNG" as im %}
                        <img src="{{ im.url }}" alt="{{ object.title }}" class="img-responsive">
                    {% empty %}
                        <p>Sem Imagem</p>
                    {% endthumbnail %}
    				<!-- Para -->
    				{% autoescape off %}
                    <p>{{ object.body|linebreaks|cut:"../../../.." }}</p>
                    {% endautoescape %}
    			</div>
            </div>
			<div class="clearfix"></div>
		</div>
	</div>

{% endblock post %}

econordeste/blog/templates/blog/entry_home.html
{% extends "blog/entry_base.html" %}

{% load thumbnail %}

{% block nav_blog %} active{% endblock %}

{% block post %}

	<!-- The new post done by user's all in the post block -->
	<div class="blog-post">
		{% for object in object_list %}
			<!-- Entry is the one post for each user -->
			<div class="entry">
				<!-- Meta for this block -->
				<div class="meta br-white col-md-3 col-sm-3">
					<!-- Date -->
					<div class="post-date"><span>{{ object.created|date:"d M" }}</span>{{ object.created|date:"Y" }}</div>
					<!-- Post Information -->
					<div class="meta-info"><i class="fa fa-user"></i> <span>{{ object.author }}</span></div>
					<div class="meta-info"><i class="fa fa-tag"></i>
						{% for tag in object.tags.all %}
					        <a href="{% url 'blog:tag_list' tag.slug %}"><span>{{ tag.name }}</span></a>
                        {% endfor %}
					</div>
				</div>
				<div class="beta br-white pull-right col-md-9 col-sm-9">
					<!-- Heading of the  post -->
					<h4><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h4>
					{% thumbnail object.image "800" crop="center" format="PNG" as im %}
                        <p><img src="{{ im.url }}" alt="{{ object.title }}" title="{{ object.title }}" class="img-responsive" /></p>
                    {% empty %}
                        <p>Sem Imagem</p>
                    {% endthumbnail %}
					<!-- Para -->
					{% autoescape off %}
                    <p>{{ object.body|striptags|truncatewords_html:75 }}</p>
                    {% endautoescape %}
				</div>
				<div class="clearfix"></div>
			</div>
		{% empty %}
			<div class="entry">
				<div class="meta col-md-12 col-sm-12 br-white">
					<p>Nenhuma notícia encontrada.</p>
				</div>
			</div>
		{% endfor %}
	</div>

	{% include "paginator.html" %}

{% endblock post %}