econordeste/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from filebrowser.sites import site

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^$', 'econordeste.core.views.home', name='home'),
    # url(r'^institucional/', 'canaa.core.views.institutional',
    #     name='institutional'),
    url(r'^projeto/$', 'econordeste.core.views.project', name='project'),
    url(r'^soundcloud/$', 'econordeste.core.views.soundcloud',
        name='soundcloud'),
    url(r'^equipe/$', 'econordeste.core.views.team', name='team'),
    url(r'^jogos/$', 'econordeste.core.views.games', name='games'),
    url(r'^contato/$', 'econordeste.core.views.contact', name='contact'),

    url(r'^noticias/', include('econordeste.blog.urls', namespace='blog')),
    url(r'^agenda/', include('econordeste.event.urls', namespace='event')),

    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # tinymce
    url(r'^tinymce/', include('tinymce.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# )

econordeste/core/models.py
# coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

import uuid
import os

from filebrowser.fields import FileBrowseField
from sorl.thumbnail import ImageField
from tinymce import models as tinymce_models

try:
    from PIL import Image, ImageOps
except ImportError:
    import Image
    import ImageOps


STATE_CHOICES = (
    ('AC', u'Acre'),
    ('AL', u'Alagoas'),
    ('AP', u'Amapá'),
    ('AM', u'Amazonas'),
    ('BA', u'Bahia'),
    ('CE', u'Ceará'),
    ('DF', u'Distrito Federal'),
    ('ES', u'Espírito Santo'),
    ('GO', u'Goiás'),
    ('MA', u'Maranhão'),
    ('MT', u'Mato Grosso'),
    ('MS', u'Mato Grosso do Sul'),
    ('MG', u'Minas Gerais'),
    ('PA', u'Pará'),
    ('PB', u'Paraíba'),
    ('PR', u'Paraná'),
    ('PE', u'Pernambuco'),
    ('PI', u'Piauí'),
    ('RJ', u'Rio de Janeiro'),
    ('RN', u'Rio Grande do Norte'),
    ('RS', u'Rio Grande do Sul'),
    ('RO', u'Rondônia'),
    ('RR', u'Roraima'),
    ('SC', u'Santa Catarina'),
    ('SP', u'São Paulo'),
    ('SE', u'Sergipe'),
    ('TO', u'Tocantins'),
)

BANNER_CHOICES = (
    (1, _(u'Super Banner (Home)')),
    # (2, _(u'Banner Secundário (Home)')),
    (3, _(u'Popup Banner')),
)


class Social(models.Model):
    name = models.CharField(_(u'Nome'), max_length=50,
                            help_text='Ex: Facebook')
    link = models.URLField(_(u'Link'),
                           help_text='Ex: http://www.facebook.com/usuario')

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Mídia Social')
        verbose_name_plural = _(u'Mídias Sociais')
        ordering = ['name']


class Enterprise(models.Model):
    name = models.CharField(_(u'Nome'), max_length=100)
    description = models.CharField(_(u'Descrição'), max_length=100,
                                   blank=True, null=True)
    cnpj = models.CharField(_(u'CNPJ'), max_length=20,
                            help_text='99.999.999/9999-99')
    address = models.CharField(_(u'Endereço'), max_length=200)
    number = models.CharField(_(u'Número'), max_length=10)
    complement = models.CharField(_(u'Complemento'), max_length=100,
                                  blank=True, null=True)
    cep = models.CharField(_(u'CEP'), max_length=9, help_text='99999-999',
                           blank=True, null=True)
    district = models.CharField(_(u'Bairro'), max_length=100)
    city = models.CharField(_(u'Cidade'), max_length=100)
    state = models.CharField(_(u'UF'), max_length=2, choices=STATE_CHOICES)
    country = models.CharField(_(u'País'), max_length=50)
    phone1 = models.CharField(_(u'Fone 1'), max_length=20,
                              help_text='(99) 9999-9999')
    phone2 = models.CharField(_(u'Fone 2'), max_length=20,
                              help_text='(99) 9999-9999', blank=True,
                              null=True)
    phone3 = models.CharField(_(u'Fone 3 (Fax)'), max_length=20,
                              help_text='(99) 9999-9999', blank=True,
                              null=True)
    email = models.EmailField(_(u'Email'))
    site = models.URLField(_(u'Site'))
    socials = models.ManyToManyField('Social',
                                     verbose_name=_(u'Mídias Sociais'))

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Empresa')
        verbose_name_plural = _(u'Empresa')


class Category(models.Model):
    name = models.CharField(_(u'Nome da Categoria'), max_length=200)
    slug = models.SlugField(_(u'Link no Site'), max_length=200,
                            unique=True)
    acronym = models.CharField(_(u'Sigla'), max_length=50, blank=True,
                               null=True)

    def get_absolute_url(self):
        return reverse('blog:category_list', kwargs={'pk': self.pk})

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Categoria')
        verbose_name_plural = _(u'Categorias')
        ordering = ['name']


class BannerManager(models.Manager):
    def get_queryset(self):
        return super(BannerManager,
                     self).get_queryset().all()


class BannerPublishedManager(models.Manager):
    def get_queryset(self):
        return super(BannerPublishedManager,
                     self).get_queryset().filter(publish=True)


class Banner(models.Model):
    def get_file_path(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), ext)
        return os.path.join('banner', filename)

    type = models.IntegerField(_(u'Banner'), choices=BANNER_CHOICES, default=1)
    image = ImageField(_(u'Banner'), upload_to=get_file_path)
    title = models.CharField(_(u'Título do banner'), max_length=100)
    link = models.URLField(_(u'Link do banner'), blank=True, null=True)
    publish = models.BooleanField(_(u'Visível no site?'), default=True)

    objects = BannerManager()
    published = BannerPublishedManager()

    def admin_image(self):
        return '<img src="%s" width="200" />' % self.image.url
    admin_image.allow_tags = True
    admin_image.short_description = 'Imagem'

    def save(self, *args, **kwargs):
        if not self.id and not self.image:
            return

        super(Banner, self).save(*args, **kwargs)

        image = Image.open(self.image)

        def scale_dimensions(width, height, longest_side):
            if width > height:
                if width > longest_side:
                    ratio = longest_side*1./width
                    return (int(width*ratio), int(height*ratio))
                elif height > longest_side:
                    ratio = longest_side*1./height
                    return (int(width*ratio), int(height*ratio))
            return (width, height)

        if self.type == 2:
            side = 500
        else:
            side = 1280

        (width, height) = image.size
        (width, height) = scale_dimensions(width, height, longest_side=side)

        size = (width, height)
        """ redimensiona esticando """
        # image = image.resize(size, Image.ANTIALIAS)
        """ redimensiona proporcionalmente """
        image.thumbnail(size, Image.ANTIALIAS)
        """ redimensiona cortando para encaixar no tamanho """
        # image = ImageOps.fit(image, size, Image.ANTIALIAS)
        image.save(self.image.path, 'JPEG', quality=99)

    def __unicode__(self):
        return unicode(self.title)

    class Meta:
        verbose_name = _(u'Banner')
        verbose_name_plural = _(u'Banners')


class Team(models.Model):
    def get_file_path(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), ext)
        return os.path.join('team', filename)

    name = models.CharField(_(u'Nome'), max_length=30)
    description = models.CharField(_(u'Descrição'), max_length=200)
    image = models.ImageField(_(u'Foto'), upload_to=get_file_path,
                              blank=True, null=True)

    def admin_image(self):
        if self.image.url:
            return '<img src="%s" width="60" />' % self.image.url
        else:
            return 'Sem imagem.'
    admin_image.allow_tags = True
    admin_image.short_description = 'Foto'

    def save(self, *args, **kwargs):
        if not self.id and not self.image:
            return

        super(Team, self).save(*args, **kwargs)

        image = Image.open(self.image)

        def scale_dimensions(width, height, longest_side):
            if width > height:
                if width > longest_side:
                    ratio = longest_side*1./width
                    return (int(width*ratio), int(height*ratio))
                elif height > longest_side:
                    ratio = longest_side*1./height
                    return (int(width*ratio), int(height*ratio))
            return (width, height)

        side = 400

        (width, height) = image.size
        (width, height) = scale_dimensions(width, height, longest_side=side)

        size = (width, height)
        """ redimensiona esticando """
        # image = image.resize(size, Image.ANTIALIAS)
        """ redimensiona proporcionalmente """
        # image.thumbnail(size, Image.ANTIALIAS)
        """ redimensiona cortando para encaixar no tamanho """
        image = ImageOps.fit(image, size, Image.ANTIALIAS)
        image.save(self.image.path, 'JPEG', quality=99)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _(u'Equipe')
        verbose_name_plural = _(u'Equipe')
        ordering = ['name']


class Project(models.Model):
    title = models.CharField(_(u'Título'), max_length=200)
    body = tinymce_models.HTMLField(_(u'Conteúdo'))

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _(u'Projeto')
        verbose_name_plural = _(u'Projeto')
        ordering = ['title']


class Games(models.Model):
    title = models.CharField(_(u'Título'), max_length=200)
    body = tinymce_models.HTMLField(_(u'Conteúdo'))

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _(u'Jogo')
        verbose_name_plural = _(u'Jogos')
        ordering = ['title']


class Video(models.Model):
    title = models.CharField(_(u'Título'), max_length=100)
    body = models.TextField(_(u'Descrição'), blank=True, null=True)
    url = models.URLField(_(u'Endereço do Vídeo'))
    embed = models.URLField(_(u'Embed'), blank=True, null=True, editable=False)

    def __unicode__(self):
        return unicode(self.title)

    def save(self, *args, **kwargs):
        self.embed = self.url.replace('watch?v=', 'embed/')
        super(Video, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _(u'Vídeo')
        verbose_name_plural = _(u'Vídeos')
        ordering = ['-pk']


class Logo(models.Model):

econordeste/core/forms.py
# coding: utf-8
from django import forms
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives

from econordeste.core.models import Team


class ContactForm(forms.Form):
    name = forms.CharField(label=u'Nome',
                           widget=forms.TextInput(
                               attrs={'class': 'form-control',
                                      'placeholder': 'Nome:'}))
    email = forms.EmailField(label=u'E-mail',
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': 'E-mail:'}))
    message = forms.CharField(label=u'Mensagem',
                              widget=forms.Textarea(
                                  attrs={'class': 'form-control', 'rows': 3,
                                         'placeholder': 'Mensagem:'}))

    def send_mail(self):
        subject = u'Contato do site (%s)' % self.cleaned_data['name']
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        message = render_to_string('contact_mail.txt', context)
        message_html = render_to_string('contact_mail.html', context)
        msg = EmailMultiAlternatives(subject, message,
                                     'no-reply@econordeste.gov.br',
                                     ['imprensa@econordeste.gov.br'])

        msg.attach_alternative(message_html, 'text/html')
        msg.send()


class TeamForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(
                                  attrs={'cols': 60, 'rows': 6,
                                         'maxlength': 200}))

    class Meta:
        model = Team

econordeste/core/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.template import RequestContext

from econordeste.context_processors import enterprise_proc

from econordeste.core.models import Banner, Team, Project, Games
from econordeste.blog.models import Entry

from econordeste.core.forms import ContactForm


def home(request):
    context = {}
    context['blog_list'] = Entry.published.all()[:16]
    context['super_banner_list'] = Banner.published.filter(type=1)
    context['second_banner_list'] = Banner.published.filter(type=2)
    context['popup_banner_list'] = Banner.published.filter(type=3)[:1]

    return render(request, 'home.html', context,
                  context_instance=RequestContext(request,
                                                  processors=[enterprise_proc]
                                                  ))


def contact(request):
    context = {}

    # contact
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.send_mail()
            context['contact_success'] = True
    else:
        form = ContactForm()

    context['contact_form'] = form

    return render(request, 'contact.html', context,
                  context_instance=RequestContext(request,
                                                  processors=[enterprise_proc]
                                                  ))


def soundcloud(request):
    context = {}

    pagina = request.GET.get('pagina', '')
    if pagina:
        context['pagina'] = pagina

    return render(request, 'radio.html', context)
    # return redirect('http://saloa.pe.gov.br/transparencia/')


def team(request):
    context = {}
    context['team_list'] = Team.objects.all()

    return render(request, 'team.html', context,
                  context_instance=RequestContext(request,
                                                  processors=[enterprise_proc]
                                                  ))


def project(request):
    context = {}
    context['project_list'] = Project.objects.all()

    return render(request, 'project.html', context,
                  context_instance=RequestContext(request,
                                                  processors=[enterprise_proc]
                                                  ))


def games(request):
    context = {}
    context['games_list'] = Games.objects.all()

    return render(request, 'games.html', context,
                  context_instance=RequestContext(request,
                                                  processors=[enterprise_proc]
                                                  ))

econordeste/core/templates/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt" class="no-js">
	<head>
		<meta charset="utf-8">
		<!-- Title here -->
		<title>{{ enterprise.name }} - {{ enterprise.description }}{% block title %}{% endblock title %}</title>
		<!-- Description, Keywords and Author -->
		<meta name="description" content="Projeto Águas de Garanhuns">
		<meta name="keywords" content="eco, ecologia, garanhuns, pernambuco, petrobras, nordeste, aguas, garanhuns, nascente">
		<meta name="author" content="OW7">

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Styles -->
		<!-- Bootstrap CSS -->
		<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
		<!-- Animate CSS -->
		<link href="{{ STATIC_URL }}css/animate.min.css" rel="stylesheet">
		<!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
		<link href="{{ STATIC_URL }}css/settings.css" rel="stylesheet">
		<!--[if IE ]><link rel="stylesheet" href="css/settings-ie8.css"><![endif]-->
		<!-- Portfolio CSS -->
		<link href="{{ STATIC_URL }}css/prettyPhoto.css" rel="stylesheet">
		<!-- Countdown CSS -->
		<link href="{{ STATIC_URL }}css/jquery.countdown.css" rel="stylesheet">
		<!-- Font awesome CSS -->
		<link href="{{ STATIC_URL }}css/font-awesome.min.css" rel="stylesheet">
		<!-- Custom CSS -->
		<link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
		<!--[if IE]><link rel="stylesheet" href="css/ie-style.css"><![endif]-->

		<!-- Favicon -->
		<link rel="shortcut icon" href="{{ STATIC_URL }}ico/favicon.ico">

		{% block extra_js_top %}

		{% endblock extra_js_top %}
	</head>

	<body>

		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&appId=309206689218714&version=v2.0";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>

		<!-- Body Wrapper -->
		<div class="wrapper">

			<!-- Header Start -->
			<div class="header">
				<!-- Header Information -->
				<div class="header-info">
					<div class="container">
						<div class="row">
							<div class="col-md-3 col-sm-3">
								<div class="logo-aguas">
									Projeto
									<a href="{% url 'home' %}"><img src="{{ STATIC_URL }}img/logo_aguas-de-garanhuns.png" class="img-responsive" alt="Águas de Garanhuns" title="Início" /></a>
								</div>
							</div>
							<div class="col-md-3 col-sm-3">
								<!-- Search Box -->
								<br>
								<div class="search">
									<form role="form" action="/noticias/" method="get">
										<div class="input-group">
											<input id="search" name="search" type="text" class="form-control" placeholder="Buscar notícia">
											<span class="input-group-btn">
												<button class="btn" type="submit"><i class="fa fa-search"></i></button>
											</span>
										</div>
									</form>
								</div>
							</div>

							<div class="col-md-6 col-sm-6">
								{% for logo in logo_list %}
									<div class="col-md-{% if forloop.counter == 1 %}5{% else %}4{% endif %} col-sm-{% if forloop.counter == 1 %}5{% else %}4{% endif %}">
										{% if forloop.counter == 1 %}Patrocínio{% else %}<br>{% endif %}
										<div class="logo-top">
											<a href="{{ logo.link }}" target="_blank">
												<img src="{{ logo.image.url }}" class="img-responsive" alt="{{ logo.title }}" title="{{ logo.title }}" />
											</a>
										</div>
									</div>
								{% endfor %}
								<!-- <div class="col-md-4 col-sm-4">
									<br>
									<div class="logo-top">
										<a href="http://www.petrobras.com.br/" target="_blank">
											<img src="{{ STATIC_URL }}img/logo_governo-federal.jpg" class="img-responsive" alt="" />
										</a>
									</div>
								</div> -->
								<div class="col-md-3 col-sm-3">
									Executora
									<div class="logo-top">
										<img src="{{ STATIC_URL }}img/logo_eco-nordeste.png" class="img-responsive" alt="" />
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Header Navigation -->
				<div class="header-navigation">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<!-- Bootstrap Navbar -->
								<nav class="navbar navbar-default" role="navigation">
									<div class="col-md-4">
										<div class="logo">
											<h1><a href="{% url 'home' %}"><img src="{{ STATIC_URL }}img/logo_aguas-de-garanhuns.png" class="img-responsive" alt="" /></a></h1>
										</div>
									</div>
									<!-- Brand and toggle get grouped for better mobile display -->
									<div class="col-md-8">
										<div class="navbar-header">
											<button type="button" class="navbar-toggle br-white" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
												<span class="sr-only">Toggle navigation</span>
												<span class="icon-bar br-black"></span>
												<span class="icon-bar br-black"></span>
												<span class="icon-bar br-black"></span>
											</button>
										</div>
									</div>
									<!-- Collect the nav links, forms, and other content for toggling -->
									<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
											<li>
												<a href="{% url 'project' %}" class="br-white">
													<span class="link-title{% block nav_project %}{% endblock %}">Projeto</span>
												</a>
											</li>
											<li>
												<a href="{% url 'blog:home' %}" class="br-white">
													<span class="link-title{% block nav_blog %}{% endblock %}">Notícias</span>
												</a>
											</li>
											<li>
												<a href="{% url 'event:home' %}" class="br-white">
													<span class="link-title{% block nav_event %}{% endblock %}">Agenda</span>
												</a>
											</li>
											<li>
												<a href="{% url 'team' %}" class="br-white">
													<span class="link-title{% block nav_team %}{% endblock %}">Equipe</span>
												</a>
											</li>
											<li>
												<a href="{% url 'games' %}" class="br-white">
													<span class="link-title{% block nav_games %}{% endblock %}">Jogos</span>
												</a>
											</li>
											<li>
												<a href="{% url 'contact' %}" class="br-white">
													<span class="link-title{% block nav_contact %}{% endblock %}">Contato</span>
												</a>
											</li>
										</ul>
									</div><!-- /.navbar-collapse -->
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Header End -->

			{% block content %}

			{% endblock content %}

			<!-- Footer Start -->

			<div class="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="col-md-4 col-sm-4">
								<!-- Footer Widget -->
								<div class="footer-widget">
									<address>
										<i class="fa fa-home br-black"></i> {{ enterprise.address }}, {{ enterprise.number }} <br />
										&nbsp; &nbsp; &nbsp; &nbsp; {{ enterprise.district }}, {{ enterprise.city }}/{{ enterprise.state }}  <br />
										&nbsp; &nbsp; &nbsp; &nbsp; {{ enterprise.country }} - {{ enterprise.cep }} <br /><br />
										<span><i class="fa fa-phone br-black"></i> {{ enterprise.phone1 }}</span>
										<span><i class="fa fa-envelope-o br-black"></i> <a href="{% url 'contact' %}">{{ enterprise.email }}</a></span>
									</address>
								</div>
							</div>
							<div class="col-md-3 col-sm-3">
								<a href="{% url 'games' %}">
									<img src="{{ STATIC_URL }}img/games-banner.jpg" alt="" class="img-responsive" style="margin-top: 30px;">
								</a>
								<!-- <ul>
									<li>
										<a href="{% url 'project' %}">Projeto</a>
									</li>
									<li>
										<a href="{% url 'blog:home' %}">Notícias</a>
									</li>
									<li>
										<a href="{% url 'event:home' %}">Agenda</a>
									</li>
									<li>
										<a href="{% url 'team' %}">Equipe</a>
									</li>
									<li>
										<a href="{% url 'games' %}">Jogos</a>
									</li>
									<li>
										<a href="{% url 'contact' %}">Contato</a>
									</li>
								</ul> -->
							</div>
							<div class="col-md-1"></div>
							<div class="col-md-4 col-sm-4">
								<!-- Footer Widget -->
								<div class="footer-widget">
									<div class="fb-like-box" data-href="https://www.facebook.com/projetoaguasdegaranhuns" class="img-responsive" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
								</div>
							</div>
						</div>
					</div>
					<!-- Footer Copyright -->
					<div class="footer-copyright">
						<div class="col-md-10 col-sm-10">
							<p>&copy; Copyright 2014-{% now "Y" %} <strong>Eco Nordeste</strong></p>
						</div>
						<div class="col-md-2 col-sm-2">
							<p class="pull-right"><a href="http://ow7.com.br/">OW7</a></p>
						</div>
					</div>
				</div>
			</div>

			<!-- Footer End -->

		</div>
		<!-- Footer End -->

		<!-- Scroll to top -->
		<span class="totop"><a href="#"><i class="fa fa-angle-up"></i></a></span>




		<!-- Javascript files -->
		<!-- jQuery -->
		<script src="{{ STATIC_URL }}js/jquery.js"></script>
		<!-- Bootstrap JS -->
		<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
		<!-- Cycle JS -->
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.cycle.all.js"></script>
		<!-- jQuery flot -->
		<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/excanvas.min.js"></script><![endif]-->
		<script src="{{ STATIC_URL }}js/jquery.flot.min.js"></script>
		<script src="{{ STATIC_URL }}js/jquery.flot.resize.min.js"></script>
		<!-- Count To JS  -->
		<script src="{{ STATIC_URL }}js/jquery.countTo.js"></script>
		<!-- Masonry JS -->
		<script src="{{ STATIC_URL }}js/masonry.pkgd.min.js"></script>
		<script src="{{ STATIC_URL }}js/imagesloaded.pkgd.min.js"></script>
		<!-- jQuery way points -->
		<script src="{{ STATIC_URL }}js/waypoints.min.js"></script>
		<!-- jQuery prettyPhoto & Isotope -->
		<script src="{{ STATIC_URL }}js/jquery.prettyPhoto.js"></script>
		<script src="{{ STATIC_URL }}js/isotope.js"></script>
		<!-- Jquery for Countdown  -->
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.countdown.min.js"></script>
		<!-- Respond JS for IE8 -->
		<script src="{{ STATIC_URL }}js/respond.min.js"></script>
		<!-- HTML5 Support for IE -->
		<script src="{{ STATIC_URL }}js/html5shiv.js"></script>
		<!-- Custom JS -->
		<script src="{{ STATIC_URL }}js/custom.js"></script>

		<!-- This Page JavaScript -->
		<script type="text/javascript" >

			// initialize Masonry
				var $container = $('#container').masonry();
			// layout Masonry again after all images have loaded
				$container.imagesLoaded( function() {
					$container.masonry();
				});

		</script>

		{% block extra_js_bot %}

		{% endblock extra_js_bot %}

	</body>
</html>

econordeste/core/templates/contact.html
{% extends "base.html" %}

{% load thumbnail %}

{% block nav_contact %} active{% endblock %}

{% block content %}

			<!-- Inner Page Content // Start -->

			<div class="inner-page">
				<div class="container">
					<div class="row">
						<!-- Main-bar Column -->
						<div class="col-md-12">
							<div class="page-mainbar contactus">
								<!-- Heading -->
								<h3>Contato</h3>
								<!-- Contact Us Form -->
								<div class="contact-form">
									<div class="row">
										<div class="col-md-6 col-sm-6">
											{% if contact_success %}
						                    <p>Mensagem enviada com sucesso.</p>
						                    <a href="{% url 'contact' %}" class="btn btn-default">Voltar</a>
						                    {% else %}
						                    <form method="post" action=".">
						                        {% csrf_token %}
						                        {% for field in contact_form %}
						                        	<div class="form-group">
						                            {{ field }}
						                            {{ field.errors }}
						                            </div>
						                        {% endfor %}
						                        <input type="submit" class="btn btn-default" value="Enviar mensagem">
						                    </form>
						                    {% endif %}
										</div>
										<div class="col-md-6 col-sm-6">
											<!-- Google Map -->
											<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3941.962559268157!2d-36.4865086!3d-8.8830731!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7070cddcf046227%3A0xec8a2eac68ca9ec9!2sR.+Pedro+Rocha%2C+286+-+Heli%C3%B3polis%2C+Garanhuns+-+PE%2C+55295-470!5e0!3m2!1sen!2sbr!4v1421357809162" frameborder="0" style="border:0"></iframe>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Inner Page Content // End -->

{% endblock content %}

econordeste/core/templates/contact_mail.html
<p><strong>Nome:</strong> {{ name }}</p>
<p><strong>E-mail:</strong> {{ email }}</p>
<p><strong>Mensagem:</strong></p>
{{ message|linebreaks }}